environment:
  matrix:
    # - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    # - nodejs_version: "iojs"
install:
  - "npm install -g gulp"
  - "npm install -g mocha"
  - "npm install -g istanbul"
  - "npm install -g typescript"
  - "npm install -g tsd"
  - "npm install"
  - "tsd reinstall --save"
  - "npm run build"
build: off
test_script:
  - "npm run test-ci"
version: "{build}"