environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "iojs"
install:
  - "npm install -g mocha"
  - "npm install -g istanbul"
  - "npm install"
build: off
test_script:
  - "npm run test-ci"
version: "{build}"